version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.5@sha256:f0abbbd11ced29754d4d188c29e9320b613481ec162b6ea5d3a8b6bdd8e5fa54
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  fastify-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.fastify-app.rule=Host(`fastify-starter.traefik.me`)"
      - "traefik.http.services.fastify-app.loadbalancer.server.port=3000"
    environment:
      NODE_ENV: production
    command: yarn start:prod
