version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.6@sha256:171c9c3565b29f6c133f1c1b43c5d4e5853415198e9e1078c001f8702ff66aec
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  fastify-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.fastify-app.rule=Host(`fastify-starter.traefik.me`)"
      - "traefik.http.services.fastify-app.loadbalancer.server.port=3000"
    environment:
      NODE_ENV: production
    command: yarn start:prod
