version: "3.8"

services:
  reverse-proxy:
    image: traefik:v3.7@sha256:7d3688531da5f5acb3c7d9d2f41fc389b80884e07dc598d66d54500f21c82c87
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  fastify-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.fastify-app.rule=Host(`fastify-starter.traefik.me`)"
      - "traefik.http.services.fastify-app.loadbalancer.server.port=3000"
    environment:
      NODE_ENV: production
    command: yarn start:prod
