name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Fly
        run: flyctl deploy --image registry.fly.io/fastify-starter:main-25cbfa6e3719202bb68afd998c256bfda54ace33 --wait-timeout 300
